from django.urls import path
from MobileApp.views import *

urlpatterns = [
    path('',index,name="index"),
    path('index/',index,name="user_index"),
    path('component-accordion/',component_accordion,name="component_accordion"),
    path('component-actions/',component_actions,name="component_actions"),
    path('component-buttons/',component_buttons,name="component_buttons"),
    path('component-alerts/', component_alerts, name = 'component_alerts'),
    path('component-cards/',component_cards,name="component_cards"),
    path('component-charts/',component_charts,name="component_charts"),
    path('component-collapse/',component_collapse,name="component_collapse"),
    path('component-colors/',component_colors,name="component_colors"),
    path('component-footer-bar/',component_footer_bar,name="component_footer_bar"),
    path('component-header-bar/',component_header_bar,name="component_header_bar"),
    path('component-inputs/',component_inputs,name="component_inputs"),
    path('component-list-groups/',component_list_groups,name="component_list_groups"),
    path('component-menus/',component_menus,name="component_menus"),
    path('component-tables/',component_tables,name="component_tables"),
    path('component-typography/',component_typography,name="component_typography"),
    path('components/',components,name="components"),
    path('index-crypto-waves/',index_crypto_waves,name="index_crypto_waves"),
    path('index-waves/',index_waves,name="index_waves"),
    path('menu-add-card/',menu_add_card,name="menu_add_card"),
    path('menu_exchange/',menu_exchange,name="menu_exchange"),
    path('menu-friends-transfer/',menu_friends_transfer,name="menu_friends_transfer"),
    path('menu-highlights/',menu_highlights,name="menu_highlights"),
    path('menu-notifications/',menu_notifications,name="menu_notifications"),
    path('logout/',menu_sidebar,name="menu_sidebar"),
    path('logout/',menu_transfer,name="menu_transfer"),
    path('logout/',page_activity,name="page_activity"),
    path('logout/',page_cards_add,name="page_cards_add"),
    path('logout/',page_cards_single,name="page_cards_single"),
    path('logout/',page_crypto_report,name="page_crypto_report"),
    path('logout/',page_forgot_1,name="page_forgot_1"),
    path('logout/',page_goals,name="page_goals"),
    path('logout/',page_payment_bill,name="page_payment_bill"),
    path('logout/',page_payment_exchange,name="page_payment_exchange"),
    path('logout/',page_payment_request,name="page_payment_request"),
    path('logout/',page_payment_search,name="page_payment_search"),
    path('logout/',page_payment_transfer,name="page_payment_transfer"),
    path('logout/',page_payments,name="page_payments"),
    path('logout/',page_profile,name="page_profile"),
    path('logout/',page_reports,name="page_reports"),
    path('logout/',page_signin_1,name="page_signin_1"),
    path('logout/',page_wallet,name="page_wallet"),
    path('logout/',pages_stacked,name="pages_stacked"),
    path('logout/',pages,name="pages"),
    path('logout/',walkthrough_slide,name="walkthrough_slide"),

]