# Generated by Django 4.2.6 on 2024-01-17 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ENG", models.CharField(max_length=300, unique=True)),
                ("name_AMH", models.CharField(max_length=300, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_EC",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "year_GC",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("is_interval", models.BooleanField(default=False)),
                (
                    "year_start_EC",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "year_start_GC",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("year_end_EC", models.CharField(blank=True, max_length=50, null=True)),
                ("year_end_GC", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["year_EC"],
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_ENG", models.CharField(max_length=300)),
                ("title_AMH", models.CharField(blank=True, max_length=300, null=True)),
                ("composite_key", models.CharField(max_length=300, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "type_of",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yearly", "Yearly"),
                            ("quarterly", "Quarterly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "for_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TimeSeriesBase.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Month",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month_ENG", models.CharField(max_length=50)),
                ("month_AMH", models.CharField(max_length=50)),
                ("number", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Quarter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_ENG", models.CharField(max_length=50)),
                ("title_AMH", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_ENG", models.CharField(max_length=50)),
                ("title_AMH", models.CharField(max_length=50)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_ENG", models.CharField(max_length=300, unique=True)),
                ("title_AMH", models.CharField(max_length=300, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Amount_ENG", models.CharField(max_length=50)),
                ("Amount_AMH", models.CharField(blank=True, max_length=50, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="TimeSeriesBase.measurement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Indicator_Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_actual", models.BooleanField()),
                (
                    "for_datapoint",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TimeSeriesBase.datapoint",
                    ),
                ),
                (
                    "for_indicator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TimeSeriesBase.indicator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="indicator",
            name="measurement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="TimeSeriesBase.measurement",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="TimeSeriesBase.indicator",
            ),
        ),
        migrations.CreateModel(
            name="DataValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(blank=True, max_length=40, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "for_datapoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datavalue_set",
                        to="TimeSeriesBase.datapoint",
                    ),
                ),
                (
                    "for_indicator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TimeSeriesBase.indicator",
                    ),
                ),
                (
                    "for_month",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TimeSeriesBase.month",
                    ),
                ),
                (
                    "for_quarter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TimeSeriesBase.quarter",
                    ),
                ),
                (
                    "for_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="TimeSeriesBase.source",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="TimeSeriesBase.topic",
            ),
        ),
    ]
