# Generated by Django 4.2.6 on 2023-11-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavalue',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
