# Generated by Django 4.2.6 on 2023-10-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='for_catagory',
            new_name='for_category',
        ),
    ]
