# Generated by Django 4.2.6 on 2023-11-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
