# Generated by Django 4.2.6 on 2024-01-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TimeSeriesBase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="op_type",
            field=models.CharField(
                blank=True,
                choices=[("sum", "Sum"), ("average", "Average")],
                max_length=60,
                null=True,
            ),
        ),
    ]
