# Generated by Django 4.2.13 on 2024-05-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardtopic',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='dashboardtopic',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
