# Generated by Django 4.2.13 on 2024-05-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0002_alter_dashboardtopic_options_dashboardtopic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavalue',
            name='value_entrance_type',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('1month', '1 Month'), ('2month', '2 Month'), ('3month', '3 Month'), ('4month', '4 Month'), ('5month', '5 Month'), ('6month', '6 Month'), ('7month', '7 Month'), ('8month', '8 Month'), ('9month', '9 Month'), ('10month', '10 Month'), ('11month', '11 Month'), ('12month', '12 Month')], max_length=15, null=True),
        ),
    ]
