# Generated by Django 4.2.6 on 2023-11-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0002_alter_datavalue_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datavalue',
            name='for_source',
        ),
        migrations.AddField(
            model_name='datavalue',
            name='for_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TimeSeriesBase.source'),
        ),
    ]
