# Generated by Django 4.2.6 on 2023-11-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0002_indicator_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavalue',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
