# Generated by Django 4.2.6 on 2024-01-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TimeSeriesBase", "0003_alter_indicator_op_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quarter",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
