# Generated by Django 4.2.6 on 2024-05-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0003_alter_project_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='for_catgory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TimeSeriesBase.category'),
        ),
    ]
