# Generated by Django 4.2.6 on 2023-11-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0004_category_is_deleted_topic_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
