# Generated by Django 4.2.6 on 2024-05-26 09:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0004_alter_project_for_catgory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ENG', models.CharField(max_length=300, unique=True)),
                ('title_AMH', models.CharField(max_length=300, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('is_dashboard_visible', models.BooleanField(default=False)),
                ('for_catgory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TimeSeriesBase.category')),
            ],
        ),
    ]
