# Generated by Django 4.2.6 on 2023-11-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0005_datapoint_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
