# Generated by Django 4.2.6 on 2023-11-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0006_source_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeSeriesBase.measurement'),
        ),
    ]
