# Generated by Django 4.2.6 on 2023-10-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0006_measurement_created_measurement_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='for_category',
            field=models.ManyToManyField(blank=True, null=True, to='TimeSeriesBase.category'),
        ),
    ]
