# Generated by Django 4.2.6 on 2024-01-26 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TimeSeriesBase", "0007_alter_indicator_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicator",
            name="is_public",
        ),
    ]
