# Generated by Django 4.2.6 on 2023-11-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0007_indicator_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='Measure',
        ),
    ]
