# Generated by Django 4.2.6 on 2023-11-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0009_alter_measurement_amount_amh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='topic',
        ),
        migrations.AddField(
            model_name='category',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TimeSeriesBase.topic'),
        ),
    ]
