# Generated by Django 4.2.6 on 2024-02-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0009_indicator_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='measurement_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
