# Generated by Django 4.2.6 on 2024-02-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0010_indicator_measurement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='measurement_name',
        ),
    ]
