# Generated by Django 4.2.6 on 2023-11-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0010_remove_topic_user_remove_category_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
