# Generated by Django 4.2.6 on 2023-10-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0010_datapoint_created_at_datapoint_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='is_interval',
            field=models.BooleanField(default=False),
        ),
    ]
