# Generated by Django 4.2.6 on 2023-11-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0011_alter_source_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
