# Generated by Django 4.2.6 on 2023-10-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0012_month_created_at_month_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='months',
            field=models.ManyToManyField(blank=True, to='TimeSeriesBase.month'),
        ),
    ]
