# Generated by Django 4.2.6 on 2024-05-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0012_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ENG', models.CharField(max_length=300, unique=True)),
                ('title_AMH', models.CharField(max_length=300, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['number']},
        ),
    ]
