# Generated by Django 4.2.6 on 2024-05-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0013_dashboardtopic_alter_month_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtopic',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
