# Generated by Django 4.2.6 on 2023-11-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0014_book_remove_source_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='source',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
