# Generated by Django 4.2.6 on 2024-05-21 09:30

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0014_dashboardtopic_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtopic',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
