# Generated by Django 4.2.6 on 2023-10-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0015_alter_datavalue_for_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavalue',
            name='for_measurement',
            field=models.ManyToManyField(blank=True, to='TimeSeriesBase.measurement'),
        ),
        migrations.AlterField(
            model_name='datavalue',
            name='for_source',
            field=models.ManyToManyField(blank=True, to='TimeSeriesBase.source'),
        ),
    ]
