# Generated by Django 4.2.6 on 2023-10-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0016_alter_datavalue_for_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='title_AMH',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
