# Generated by Django 4.2.6 on 2024-05-23 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0016_category_dashboard_category_indicator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavalue',
            name='for_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_value', to='TimeSeriesBase.indicator'),
        ),
    ]
