# Generated by Django 4.2.6 on 2023-10-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0017_alter_indicator_title_amh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='title_AMH',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
