# Generated by Django 4.2.6 on 2024-05-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0017_alter_datavalue_for_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dashboard_category_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TimeSeriesBase.indicator'),
        ),
    ]
