# Generated by Django 4.2.6 on 2023-12-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0018_remove_indicator_point_for_measurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator_point',
            name='type_of',
        ),
        migrations.AddField(
            model_name='indicator',
            name='type_of',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], max_length=60, null=True),
        ),
    ]
