# Generated by Django 4.2.6 on 2024-05-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0018_alter_category_dashboard_category_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dashboard_category_indicator',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='op_type',
            field=models.CharField(choices=[('none', 'none'), ('sum', 'Sum'), ('average', 'Average')], default='sum', max_length=60),
        ),
        migrations.AddField(
            model_name='category',
            name='dashboard_category_indicator',
            field=models.ManyToManyField(to='TimeSeriesBase.indicator'),
        ),
    ]
