# Generated by Django 4.2.6 on 2024-05-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0019_remove_category_dashboard_category_indicator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dashboard_category_indicator',
        ),
        migrations.RemoveField(
            model_name='category',
            name='dashboard_topic',
        ),
    ]
