# Generated by Django 4.2.6 on 2023-12-20 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0019_remove_indicator_point_type_of_indicator_type_of'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ['year_EC']},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='quarter',
            old_name='quarter',
            new_name='title_AMH',
        ),
        migrations.RemoveField(
            model_name='quarter',
            name='year',
        ),
        migrations.AddField(
            model_name='quarter',
            name='title_ENG',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
