# Generated by Django 4.2.6 on 2024-05-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0020_remove_category_dashboard_category_indicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='is_dashboard_visible',
            field=models.BooleanField(default=False),
        ),
    ]
