# Generated by Django 4.2.6 on 2023-12-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0021_quarter_created_at_quarter_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarter',
            options={'ordering': ['created_at']},
        ),
    ]
