# Generated by Django 4.2.6 on 2023-12-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0022_alter_quarter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='datavalue',
            name='value',
            field=models.FloatField(blank=True, max_length=40, null=True),
        ),
    ]
