# Generated by Django 4.2.6 on 2023-12-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0023_alter_month_options_alter_datavalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
