# Generated by Django 4.2.6 on 2024-01-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0025_remove_datapoint_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
