# Generated by Django 4.2.6 on 2024-01-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0026_alter_datapoint_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='year_EC',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='year_GC',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
