# Generated by Django 4.2.6 on 2024-01-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0027_alter_datapoint_year_ec_alter_datapoint_year_gc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title_AMH',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
