# Generated by Django 4.2.6 on 2024-01-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0028_alter_topic_title_amh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_AMH',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ENG',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_ENG',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
