# Generated by Django 4.2.6 on 2024-01-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSeriesBase', '0030_alter_category_name_amh_alter_category_name_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title_ENG',
            field=models.CharField(max_length=300),
        ),
    ]
