# Generated by Django 4.2.6 on 2024-01-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TimeSeriesBase", "0032_remove_datapoint_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="title_ENG",
            field=models.CharField(max_length=300),
        ),
    ]
