# Generated by Django 4.2.6 on 2024-01-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TimeSeriesBase", "0033_alter_topic_title_eng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="title_ENG",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
