# Generated by Django 4.2.6 on 2023-12-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_remove_customuser_is_admin_remove_customuser_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
