# Generated by Django 4.2.6 on 2023-12-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_customuser_is_first_time_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_reset_password',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
